</$objtype/mkfile

LIB=libnslog.$O.a
OBJ=core.$O filter.$O gen_filter-lexer.$O gen_filter-parser.$O
HFILES=../include/nslog/nslog.h nslog_internal.h filter-parser.h filter-lexer.h

<../../nsport.mk
<../../nsportlib.mk

gen_%.c:
	cp ../../genfiles/libnslog/gen_$stem.c gen_$stem.c

filter-parser.h:
	cp ../../genfiles/libnslog/$target $target

filter-lexer.h:
	cp ../../genfiles/libnslog/$target $target
